name: C++ linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cpp_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install CMake, Clang-Tidy and JUCE dependencies
        # JUCE Linux dependencies: https://forum.juce.com/t/list-of-juce-dependencies-under-linux/15121/44
        run: |
          sudo apt update
          sudo apt install -y cmake clang-tidy
          sudo apt install -y libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev xvfb ninja-build
      - name: CMake version
        run: cmake --version
      - name: CMake build
        # DCMAKE_EXPORT_COMPILE_COMMANDS is needed for clang-tidy
        run: |
          mkdir build
          cmake -B build -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
      - name: Cpp linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1