name: Test (format)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test with cpp-linter-action
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 16
          files-changed-only: false
          thread-comments: true
          tidy-checks: '-*' # Disable "clang-tidy" checks entirely for this workflow because we're checking only code formatting here.
      - name: Fail on errors
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1