name: Test formatting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Clang-Format
        run: |
          sudo apt update
          sudo apt install -y clang-format-16
      - name: Test formatting
        run: ./test_format.sh
