name: Test lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install CMake & Clang-Tidy
        run: |
          sudo apt update
          sudo apt install -y cmake
          sudo apt install -y clang-tidy
      - name: CMake version
        run: cmake --version
      - name: CMake build
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles"
      - name: Test lint
        run: ./test_lint.sh
